/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devman.mod.prj.form;

import devman.gui.SGuiMainSessionCustom;
import devman.mod.SModConsts;
import devman.mod.prj.db.SDbProjectStagePhaseActivity;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiFieldKeyGroup;
import sa.lib.gui.SGuiParams;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanFieldKey;
import sa.lib.gui.bean.SBeanForm;

/**
 *
 * @author Sergio Flores
 */
public class SFormProjectStagePhaseActivity extends SBeanForm implements ItemListener {
    
    private SDbProjectStagePhaseActivity moRegistry;
    private SGuiFieldKeyGroup moKeyGroupStagePhase;

    /**
     * Creates new form SFormProjectActivity
     */
    public SFormProjectStagePhaseActivity(SGuiClient client, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.PU_PRJ_STG_PHS_ACT, SLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jlProject = new javax.swing.JLabel();
        moKeyProject = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel12 = new javax.swing.JPanel();
        jlProjectStage = new javax.swing.JLabel();
        moKeyProjectStage = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel14 = new javax.swing.JPanel();
        jlProjectStagePhase = new javax.swing.JLabel();
        moKeyProjectStagePhase = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel3 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        moTextCode = new sa.lib.gui.bean.SBeanFieldText();
        jPanel4 = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        moTextName = new sa.lib.gui.bean.SBeanFieldText();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jspDescription = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlDateStartPlanned = new javax.swing.JLabel();
        moDateStartPlanned = new sa.lib.gui.bean.SBeanFieldDate();
        jPanel8 = new javax.swing.JPanel();
        jlDateEndPlanned = new javax.swing.JLabel();
        moDateEndPlanned = new sa.lib.gui.bean.SBeanFieldDate();
        jPanel9 = new javax.swing.JPanel();
        jlDeliverable = new javax.swing.JLabel();
        moKeyDeliverable = new sa.lib.gui.bean.SBeanFieldKey();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel2.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlProject.setForeground(java.awt.Color.blue);
        jlProject.setText("Proyecto:*");
        jlProject.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jlProject);

        moKeyProject.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel5.add(moKeyProject);

        jPanel2.add(jPanel5);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlProjectStage.setForeground(java.awt.Color.blue);
        jlProjectStage.setText("Etapa:*");
        jlProjectStage.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel12.add(jlProjectStage);

        moKeyProjectStage.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel12.add(moKeyProjectStage);

        jPanel2.add(jPanel12);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlProjectStagePhase.setForeground(java.awt.Color.blue);
        jlProjectStagePhase.setText("Fase:*");
        jlProjectStagePhase.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel14.add(jlProjectStagePhase);

        moKeyProjectStagePhase.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel14.add(moKeyProjectStagePhase);

        jPanel2.add(jPanel14);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCode.setText("Código:*");
        jlCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlCode);

        moTextCode.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel3.add(moTextCode);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlName.setText("Nombre:*");
        jlName.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlName);

        moTextName.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel4.add(moTextName);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jspDescription.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jspDescription.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspDescription.setPreferredSize(new java.awt.Dimension(505, 150));

        jtaDescription.setColumns(20);
        jtaDescription.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtaDescription.setRows(5);
        jspDescription.setViewportView(jtaDescription);

        jPanel13.add(jspDescription);

        jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDateStartPlanned.setText("Inicio planeado:*");
        jlDateStartPlanned.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel7.add(jlDateStartPlanned);
        jPanel7.add(moDateStartPlanned);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDateEndPlanned.setText("Fin planeado:*");
        jlDateEndPlanned.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel8.add(jlDateEndPlanned);
        jPanel8.add(moDateEndPlanned);

        jPanel6.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDeliverable.setText("Entregable:");
        jlDeliverable.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel9.add(jlDeliverable);

        moKeyDeliverable.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel9.add(moKeyDeliverable);

        jPanel6.add(jPanel9);

        jPanel11.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel10.add(jPanel11, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel10, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlDateEndPlanned;
    private javax.swing.JLabel jlDateStartPlanned;
    private javax.swing.JLabel jlDeliverable;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlProject;
    private javax.swing.JLabel jlProjectStage;
    private javax.swing.JLabel jlProjectStagePhase;
    private javax.swing.JScrollPane jspDescription;
    private javax.swing.JTextArea jtaDescription;
    private sa.lib.gui.bean.SBeanFieldDate moDateEndPlanned;
    private sa.lib.gui.bean.SBeanFieldDate moDateStartPlanned;
    private sa.lib.gui.bean.SBeanFieldKey moKeyDeliverable;
    private sa.lib.gui.bean.SBeanFieldKey moKeyProject;
    private sa.lib.gui.bean.SBeanFieldKey moKeyProjectStage;
    private sa.lib.gui.bean.SBeanFieldKey moKeyProjectStagePhase;
    private sa.lib.gui.bean.SBeanFieldText moTextCode;
    private sa.lib.gui.bean.SBeanFieldText moTextName;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */
    
    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 800, 500);
        
        moKeyProject.setKeySettings(miClient, SGuiUtils.getLabelName(jlProject), true);
        moKeyProjectStage.setKeySettings(miClient, SGuiUtils.getLabelName(jlProjectStage), true);
        moKeyProjectStagePhase.setKeySettings(miClient, SGuiUtils.getLabelName(jlProjectStagePhase), true);
        moTextCode.setTextSettings(SGuiUtils.getLabelName(jlCode), 20);
        moTextName.setTextSettings(SGuiUtils.getLabelName(jlName), 100);
        moDateStartPlanned.setDateSettings(miClient, SGuiUtils.getLabelName(jlDateStartPlanned), true);
        moDateEndPlanned.setDateSettings(miClient, SGuiUtils.getLabelName(jlDateEndPlanned), true);
        moKeyDeliverable.setKeySettings(miClient, SGuiUtils.getLabelName(jlDeliverable), false);
        
        moFields.addField(moKeyProject);
        moFields.addField(moKeyProjectStage);
        moFields.addField(moKeyProjectStagePhase);
        moFields.addField(moTextCode);
        moFields.addField(moTextName);
        moFields.addField(moDateStartPlanned);
        moFields.addField(moDateEndPlanned);
        moFields.addField(moKeyDeliverable);
        
        moFields.setFormButton(jbSave);
        
        moKeyGroupStagePhase = new SGuiFieldKeyGroup(miClient);
    }
    
    private void setFieldsStatusByProject() {
        if (moKeyProject.getSelectedIndex() <= 0) {
            moKeyDeliverable.setEnabled(false);
        }
        else {
            moKeyDeliverable.setEnabled(true);
        }
    }
    
    private void itemStateChangedProject() {
        if (moKeyProject.getSelectedIndex() <= 0) {
            moKeyDeliverable.removeAllItems();
        }
        else {
            miClient.getSession().populateCatalogue(moKeyDeliverable, SModConsts.PU_PRJ_DLV, SLibConsts.UNDEFINED, new SGuiParams(moKeyProject.getValue()));
        }
        
        setFieldsStatusByProject();
    }
    
    /*
     * Public methods
     */
    
    /*
     * Overriden methods
     */
    
    @Override
    public void addAllListeners() {
        moKeyProject.addItemListener(this);
    }

    @Override
    public void removeAllListeners() {
        moKeyProject.removeItemListener(this);
    }

    @Override
    public void reloadCatalogues() {
        moKeyGroupStagePhase.initGroup();
        moKeyGroupStagePhase.addFieldKey(moKeyProject, SModConsts.PU_PRJ, SLibConsts.UNDEFINED, null);
        moKeyGroupStagePhase.addFieldKey(moKeyProjectStage, SModConsts.PU_PRJ_STG, SLibConsts.UNDEFINED, null);
        moKeyGroupStagePhase.addFieldKey(moKeyProjectStagePhase, SModConsts.PU_PRJ_STG_PHS, SLibConsts.UNDEFINED, null);
        moKeyGroupStagePhase.populateCatalogues();
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbProjectStagePhaseActivity) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            //moRegistry.setCode("");
            
            if (moRegistry.getPkProjectId() == SLibConsts.UNDEFINED) {
                moRegistry.setPkProjectId(((SGuiMainSessionCustom) miClient.getSession().getSessionCustom()).getProjectStageKey()[0]);
                moRegistry.setPkStageId(((SGuiMainSessionCustom) miClient.getSession().getSessionCustom()).getProjectStageKey()[1]);
                moRegistry.setDateStartPlanned(miClient.getSession().getCurrentDate());
                moRegistry.setDateEndPlanned(miClient.getSession().getCurrentDate());
            }
            
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moKeyProject.setValue(new int[] { moRegistry.getPkProjectId() });
        itemStateChangedProject();
        moKeyProjectStage.setValue(new int[] { moRegistry.getPkProjectId(), moRegistry.getPkStageId() });
        moKeyProjectStagePhase.setValue(new int[] { moRegistry.getPkProjectId(), moRegistry.getPkStageId(), moRegistry.getPkPhaseId()});
        moTextCode.setValue(moRegistry.getCode());
        moTextName.setValue(moRegistry.getName());
        jtaDescription.setText(moRegistry.getDescription());
        jtaDescription.setCaretPosition(0);
        moDateStartPlanned.setValue(moRegistry.getDateStartPlanned());
        moDateEndPlanned.setValue(moRegistry.getDateEndPlanned());
        moKeyDeliverable.setValue(new int[] { moRegistry.getFkDeliverableProjectId_n(), moRegistry.getFkDeliverableDeliverableId_n() });

        setFormEditable(true);
        
        moTextCode.setEditable(false);
        
        setFieldsStatusByProject();
        
        if (moRegistry.isRegistryNew()) {
            if (moRegistry.getPkProjectId() == SLibConsts.UNDEFINED) {
                moKeyGroupStagePhase.resetGroup();
            }
            else {
                moKeyProjectStagePhase.setEnabled(moKeyProjectStagePhase.getItemCount() > 0);
            }
        }
        else {
            moKeyProject.setEnabled(false);
            moKeyProjectStage.setEnabled(false);
            moKeyProjectStagePhase.setEnabled(false);
        }
        
        addAllListeners();
    }

    @Override
    public SDbProjectStagePhaseActivity getRegistry() throws Exception {
        SDbProjectStagePhaseActivity registry = moRegistry.clone();

        if (registry.isRegistryNew()) {
            registry.setPkProjectId(moKeyProjectStagePhase.getValue()[0]);
            registry.setPkStageId(moKeyProjectStagePhase.getValue()[1]);
            registry.setPkPhaseId(moKeyProjectStagePhase.getValue()[2]);
        }

        registry.setCode(moTextCode.getValue());
        registry.setName(moTextName.getValue());
        registry.setDescription(SLibUtils.textTrim(jtaDescription.getText()).replaceAll("'", "''"));
        registry.setDateStartPlanned(moDateStartPlanned.getValue());
        registry.setDateEndPlanned(moDateEndPlanned.getValue());
        //registry.setDeleted(...);
        //registry.setSystem(...);
        if (moKeyDeliverable.getSelectedIndex() <= 0) {
            registry.setFkDeliverableProjectId_n(SLibConsts.UNDEFINED);
            registry.setFkDeliverableDeliverableId_n(SLibConsts.UNDEFINED);
        }
        else {
            registry.setFkDeliverableProjectId_n(moKeyDeliverable.getValue()[0]);
            registry.setFkDeliverableDeliverableId_n(moKeyDeliverable.getValue()[1]);
        }

        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();
        
        if (validation.isValid()) {
            if (moDateStartPlanned.getValue().after(moDateEndPlanned.getValue())) {
                validation.setMessage(SGuiConsts.ERR_MSG_FIELD_DATE_ + "'" + SGuiUtils.getLabelName(jlDateStartPlanned) + "'" + SGuiConsts.ERR_MSG_FIELD_DATE_LESS_EQUAL + "'" + SGuiUtils.getLabelName(jlDateEndPlanned) + "'.");
                validation.setComponent(moDateStartPlanned);
            }
        }
        
        return validation;
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof SBeanFieldKey) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                SBeanFieldKey field = (SBeanFieldKey) e.getSource();
                
                if (field == moKeyProject) {
                    itemStateChangedProject();
                }
            }
        }
    }
}
